[package]
name = "api-calls"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2.3", features = ["full"] }
